version: '3'

services:
  app:
    build:
      context: .
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    environment:
      NODE_ENV: development
      MONGO_URI: mongodb://mongo:${MONGO_PORT}/${MONGO_DB}
    depends_on:
      - mongo
    networks:
      - mongo-network

  mongo:
    image: mongo:4.2
    container_name: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - mongo-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: example
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    depends_on:
      - mongo
    networks:
      - mongo-network
    links:
      - mongo

volumes:
  mongo-data:


networks:
  mongo-network:
    driver: bridge
